#include "UnityCG.cginc"


struct appdata
{
	float4 vertex : POSITION;
};

struct v2f
{
	float4 vertex : SV_POSITION;
};

sampler2D _MainTex;
float4 _MainTex_ST;

v2f vert(appdata v)
{
	v2f o;
	o.vertex = mul(UNITY_MATRIX_MVP, v.vertex);
//	float3 viewdir = normalize(ObjSpaceViewDir(v.vertex));
//	float t = 1 - saturate(dot(viewdir,v.normal));
//	o.color = _TColor*pow(t,_TPower);
	return o;
}

fixed4 frag(v2f i) : SV_Target
{
	return  float4(0,0.05,0.05,0);
}